### ISSUE TITLE
Is this basically replacing UnityWebRequest for remote downloads and uses real JS threads?

### ISSUE THREAD

**Issue by xucian** [transformsai/UnityWebGLHttpHandler#1]
Hey,
Coming from [here](https://github.com/VolodymyrBS/WebGLThreadingPatcher/issues/2#issuecomment-1172999287).
If title is true, this would be pretty useful, since the main thread would be freed. Just wanted to make sure I understand its purpose before trying it out.
Also, are there any major issues/limitations with it?

**Comment by MHDante** [comment]
At a high level, this is a shim that connects the .NET HTTPMessageHandler to Javascript's Fetch. (This means it doesn't work with older browsers [i.e. IE])

UnityWebRequest uses XmlHttpRequest.

Both of these use browser functions to make http requests. The browser isolation model then executes these in the background, and passes control back to the main thread. Neither approach "uses" the main thread. In this sense, there is no advantage to using UnityWebGLHttpHandler

However, the advantage of using this library is that it conforms to the HttpHandler interface. That allows it to be used with .NET libraries (like GRPC). Also, it uses fetch, which supports server side streaming. It's basically a lower level implementation of a web request for WebGL

The major limitation is that this is a generally unsupported library. I would avoid using it if you can use UWR.
